#!/usr/bin/env python3
import os
from setuptools import find_packages, setup

SETUP_DIR = os.path.dirname(__file__)
with open(os.path.join(SETUP_DIR, 'README.md')) as file:
    readme = file.read()

setup(
    name='workflux',
    version='0.5.0',    
    description='A platform-agnostic, cloud-ready framework for simplified deployment of the Common Workflow Language using a graphical web interface',
    long_description=readme,
    long_description_content_type="text/markdown",
    url='https://github.com/CompEpigen/workflUX',
    download_url="https://github.com/CompEpigen/workflUX",
    author='Kersten Henrik Breuer',
    author_email='k.breuer@dkfz.de',
    license='Apache 2.0',
    include_package_data=True,
    packages=find_packages(exclude=("tests",)),
    entry_points={
        "console_scripts": [
            "workflux=workflux.__main__:main",
        ]
    },
    extras_require={
        'testing': [
            'pytest',
        ],
    },
    install_requires=[
        "argcomplete==1.12.3",
        "bagit==1.8.1",
        "blessed==1.19.0",
        "bullet==2.2.0",
        "CacheControl==0.12.10",
        "certifi==2023.7.22",
        "chardet==4.0.0",
        "charset-normalizer==2.0.7",
        "click==8.0.3",
        "coloredlogs==15.0.1",
        "cwl-upgrader==1.2.2",
        "cwl-utils==0.11",
        "cwlformat==2020.5.19",
        "cwltool==3.0.20201203173111",
        "defusedxml==0.7.1",
        "docker==5.0.3",
        "et-xmlfile==1.1.0",
        "Flask==2.3.2",
        "Flask-Login==0.5.0",
        "Flask-SQLAlchemy==2.5.1",
        "Flask-WTF==1.0.0",
        "graphviz==0.18.2",
        "greenlet==1.1.2",
        "humanfriendly==10.0",
        "idna==3.7",
        "illusional.wdlgen==0.3.0",
        "importlib-metadata==4.8.2",
        "isodate==0.6.0",
        "itsdangerous==2.0.1",
        "janis-pipelines==0.11.6",
        "janis-pipelines.bioinformatics==0.11.3",
        "janis-pipelines.core==0.11.5",
        "janis-pipelines.pipelines==0.11.5",
        "janis-pipelines.runner==0.11.9",
        "janis-pipelines.templates==0.12.0",
        "janis-pipelines.unix==0.11.2",
        "jdcal==1.4.1",
        "Jinja2==3.1.4",
        "lark-parser==0.12.0",
        "lml==0.1.0",
        "lockfile==0.12.2",
        "lxml==4.9.1",
        "MarkupSafe==2.0.1",
        "miniwdl==1.3.3",
        "mistune==2.0.3",
        "msgpack==1.0.3",
        "mypy-extensions==0.4.3",
        "networkx==2.6.3",
        "nose==1.3.7",
        "odfpy==1.4.1",
        "openpyxl==2.5.14",
        "path==13.1.0",
        "pexpect==4.8.0",
        "progressbar2==3.55.0",
        "prov==1.5.1",
        "psutil==5.8.0",
        "ptyprocess==0.7.0",
        "pydantic==1.10.13",
        "pydot==1.4.2",
        "pyexcel==0.6.7",
        "pyexcel-ezodf==0.3.4",
        "pyexcel-io==0.6.5",
        "pyexcel-ods==0.6.0",
        "pyexcel-ods3==0.6.0",
        "pyexcel-xls==0.7.0",
        "pyexcel-xlsx==0.5.7",
        "pygtail==0.11.1",
        "pyparsing==3.0.6",
        "python-dateutil==2.8.2",
        "python-json-logger==2.0.2",
        "python-utils==2.5.6",
        "PyYAML==5.4.1",
        "rdflib==4.2.2",
        "rdflib-jsonld==0.5.0",
        "regex==2021.11.10",
        "requests==2.31.0",
        "requests-mock==1.9.3",
        "responses==0.16.0",
        "ruamel.yaml==0.16.5",
        "schema-salad==7.1.20210611090601",
        "shellescape==3.4.1",
        "six==1.16.0",
        "SQLAlchemy==1.4.27",
        "tabulate==0.8.9",
        "texttable==1.6.4",
        "trs-cli==0.7.0",
        "typing_extensions==4.0.0",
        "urllib3==1.26.18",
        "wcwidth==0.2.5",
        "websocket-client==1.2.1",
        "Werkzeug==3.0.1",
        "WTForms==3.0.0",
        "xdg==5.1.1",
        "xlrd==2.0.1",
        "xlwt==1.3.0",
        "zipp==3.6.0",
    ],
    classifiers=[
        'Development Status :: 4 - Beta',
        'Intended Audience :: Developers',
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: Apache Software License',
        'Natural Language :: English',
        'Operating System :: POSIX', 
        'Operating System :: POSIX :: Linux',    
        'Operating System :: MacOS :: MacOS X',
        'Operating System :: OS Independent',
        'Operating System :: Microsoft :: Windows',
        'Operating System :: Microsoft :: Windows :: Windows 10',
        'Operating System :: Microsoft :: Windows :: Windows 8.1', 
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Topic :: Scientific/Engineering',
        'Topic :: Scientific/Engineering :: Bio-Informatics',
        'Topic :: Scientific/Engineering :: Information Analysis',
        'Topic :: Scientific/Engineering :: Medical Science Apps.',
        'Topic :: System :: Distributed Computing',
    ]
)
